name: 'Download Kernel Repository'
description: 'Initialize and sync Android kernel source repository'

inputs:
  android_version:
    description: 'Android version (e.g., android14)'
    required: true
  kernel_version:
    description: 'Kernel version (e.g., 5.15, 6.1)'
    required: true
  os_patch_level:
    description: 'OS patch level (e.g., 2024-01)'
    required: true
  custom:
    required: false
    type: boolean
    default: false
  custom_name:
    required: false
    type: string
    default: ""

outputs:
  deprecated_branch:
    description: 'Whether the branch is deprecated'
    value: ${{ steps.sync.outputs.deprecated }}

runs:
  using: composite
  steps:
    - name: Initialize and Sync Kernel Repository
      id: sync
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        #FORMATTED_BRANCH="${{ inputs.android_version }}-${{ inputs.kernel_version }}-${{ inputs.os_patch_level }}"
        if [ ${{ inputs.custom }} ]; then
          MANIFEST_URL="https://github.com/UserXP-web/kernel_build"
          FORMATTED_BRANCH="main"
          MANIFEST_PATH_NAME="manifest/${{ inputs.custom_name }}.xml"
        else
          MANIFEST_URL="https://android.googlesource.com/kernel/manifest"
          FORMATTED_BRANCH="common-${{ inputs.android_version }}-${{ inputs.kernel_version }}-${{ inputs.os_patch_level }}"
          MANIFEST_PATH_NAME="default.xml"
        fi
          
        # Initialize repo with the target branch
        repo init -u ${MANIFEST_URL} -b ${FORMATTED_BRANCH} -m ${MANIFEST_PATH_NAME} --depth=1 --repo-rev=v2.16

        # Check if branch is deprecated
        REMOTE_BRANCH=$(git ls-remote https://android.googlesource.com/kernel/common ${FORMATTED_BRANCH})
        DEFAULT_MANIFEST_PATH=.repo/manifests/default.xml
        DEPRECATED=false
        
        if grep -q deprecated <<< $REMOTE_BRANCH; then
          sed -i "s/\"${FORMATTED_BRANCH}\"/\"deprecated\/${FORMATTED_BRANCH}\"/g" $DEFAULT_MANIFEST_PATH
          echo "⚠ Note: Branch ${FORMATTED_BRANCH} is considered deprecated."
          DEPRECATED=true
        fi
        
        echo "deprecated=$DEPRECATED" >> $GITHUB_OUTPUT
        
        # Sync kernel source
        repo --trace sync -c -j$(nproc --all) --fail-fast --no-tags --force-sync --no-clone-bundle

    - name: CORRECT stupid
      shell: bash
      if: false # inputs.custom
      run: |
        SUB_DIR="common" # sm7435
        curl -LSs "https://raw.githubusercontent.com/UserXP-web/kernel_build/refs/heads/main/correct/bootconfig.c" -o ./$CONFIG/$SUB_DIR/fs/proc/bootconfig.c
